# Generated by Django 6.0.4 on 2026-04-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_add_score_validators'),
        ('internship', '0006_rename_tasks_weeklylog_description'),
    ]

    operations = [
    ]
